apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-map
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "cv-app-ip"
spec:
  backend:
    serviceName: cv-app-frontend-service
    servicePort: 80
