apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cv-app-frontend-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cv-app-frontend-application
    spec:
      containers:
      - name: cv-app-frontend-application
        image: us.gcr.io/PROJECT_NAME/DOCKER_BACKEND_NAME # TODO: Insert project and docker-tag here
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

