apiVersion: v1
kind: Service
metadata:
  name: cv-app-frontend-service
spec:
  type: NodePort
  selector:
    app: cv-app-frontend-application
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP